---
- name: Listen for Red Hat Insights events
  hosts: localhost
  sources:
    - redhat.insights_eda.insights:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Match Malware detected-malware event
      condition: 
        event.payload.application == "malware-detection"
        and event.payload.event_type == "detected-malware"
      action:
        run_job_template:
          name: "handle-malware-detection"
          organization: Default
          job_args: 
            extra_vars: "{{ event.payload }}"
            
    - name:  Display contents of event.payload variable
      condition: event.payload is defined
      action:
        debug:
          msg: "Received: {{ event.payload }}"
          
